version: "3.9"

services:
  llm_server:
    build: .
    container_name: ai_literacy_lab_llm
    ports:
      - "8080:8080"
    networks:
      - ai_lab_net
  verifier:
    build: .
    container_name: ai_literacy_lab_verifier
    working_dir: /app
    volumes:
      - ../sandbox:/app/sandbox:ro
      - ../sandbox/cached_responses.json:/app/sandbox/cached_responses.json
    depends_on:
      - llm_server
    environment:
      - LLM_URL=http://llm_server:8080/completion
    command: ["python", "-m", "pytest", "sandbox"]
    networks:
      - ai_lab_net

networks:
  ai_lab_net:
    driver: bridge
