name: Verify Sandbox Demos

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ✅ Install Docker Compose plugin
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
            -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          docker compose version

      # 🧱 Build environment
      - name: Build environment
        run: |
          cd 00_Environment_Setup
          docker compose build

      # 🧪 Run verification suite
      - name: Run verification suite
        run: |
          cd 00_Environment_Setup
          docker compose up --abort-on-container-exit --exit-code-from verifier
